## Day 14. Task 03
## Метрики
### 0. Импорты

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

### 1. Препроцессинг
 
1. Загрузите снова тот же датафрейм, как и в прошлом задании.
2. Воспользуйтесь train_test_split с параметрами test_size=0.2, random_state=21 и получите X_train, y_train, X_test, y_test. Используйте дополнительный параметр stratify.

In [2]:
df = pd.read_csv('day-of-week-not-scaled.csv')
df

,numTrials,hour,dayofweek,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,9,20,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,6,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,7,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,8,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,9,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [3]:
X = df.drop(columns=['dayofweek'])
X

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,9,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,6,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,7,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,8,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,9,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [4]:
y = df['dayofweek']
y

0       4
1       4
2       4
3       4
4       4
       ..
1681    3
1682    3
1683    3
1684    3
1685    3
Name: dayofweek, Length: 1686, dtype: int64

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=21)

In [6]:
X_train

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
860,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
385,6,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
422,1,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
326,9,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
714,47,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1413,10,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1637,2,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1334,71,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
979,49,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1241,29,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
y_train

860     6
385     4
422     5
326     6
714     1
       ..
1413    3
1637    1
1334    3
979     0
1241    2
Name: dayofweek, Length: 1348, dtype: int64

In [8]:
X_test

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
1087,67,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,1,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
563,14,10,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1381,20,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1199,9,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,156,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1079,59,17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1222,22,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1064,50,16,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1243,37,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [9]:
y_test

1087    1
16      5
563     6
1381    3
1199    2
       ..
1411    3
1079    1
1222    2
1064    1
1243    2
Name: dayofweek, Length: 338, dtype: int64

In [10]:
y_train.value_counts(normalize=True)

3    0.234421
6    0.211424
1    0.162463
5    0.160979
2    0.088279
0    0.080861
4    0.061573
Name: dayofweek, dtype: float64

In [11]:
y_test.value_counts(normalize=True)

3    0.236686
6    0.210059
1    0.162722
5    0.159763
2    0.088757
0    0.079882
4    0.062130
Name: dayofweek, dtype: float64

### 2. SVM
 
1. Обучите SVM, используя параметры, которые оказались лучшими в прошлом задании.
2. В этот раз вам надо будет посчитать несколько метрик сразу: accuracy, precision, recall, ROC AUC.
- precision и recall должны быть посчитаны для каждого класса (используйте average='weighted')
- ROC AUC должен быть посчитан для каждого класса против каждого другого класса (все возможные попарные комбинации) и после этого примените взвешенное среднее, чтобы получить финальное значение метрики
- результат работы кода должен выглядить так же, как пример ниже:

*accuracy is 0.88757*  
*precision is 0.89267*  
*recall is 0.88757*  
*roc_auc is 0.97878*

In [12]:
svc = SVC(C=10,
          class_weight=None,
          gamma='auto',
          kernel='rbf',
          random_state=21,
          probability=True)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
y_pred_proba = svc.predict_proba(X_test)

In [15]:
print(f"accuracy is {accuracy_score(y_test, y_pred):.5f}\nprecision is {precision_score(y_test, y_pred, average='weighted'):.5f}\nrecall is {recall_score(y_test, y_pred, average='weighted'):.5f}\nroc_auc is {roc_auc_score(y_test, y_pred_proba, multi_class='ovo', average='weighted'):.5f}")

accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878

### 3. Decision tree
 
1. То же самое задание, но для дерева классификации

In [16]:
dt = DecisionTreeClassifier(class_weight='balanced',
                            criterion='gini',
                            max_depth=21,
                            random_state=21)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
y_pred_proba = dt.predict_proba(X_test)

In [17]:
print(f"accuracy is {accuracy_score(y_test, y_pred):.5f}\nprecision is {precision_score(y_test, y_pred, average='weighted'):.5f}\nrecall is {recall_score(y_test, y_pred, average='weighted'):.5f}\nroc_auc is {roc_auc_score(y_test, y_pred_proba, multi_class='ovo', average='weighted'):.5f}")

accuracy is 0.89053
precision is 0.89402
recall is 0.89053
roc_auc is 0.93793

### 4. Случайный лес
 
1. То же самое задание, но для дерева классификации

In [23]:
rf = RandomForestClassifier(class_weight=None,
                            criterion='gini',
                            max_depth=28,
                            n_estimators=50,
                            random_state=21)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_pred_proba = rf.predict_proba(X_test)

In [24]:
print(f"accuracy is {accuracy_score(y_test, y_pred):.5f}\nprecision is {precision_score(y_test, y_pred, average='weighted'):.5f}\nrecall is {recall_score(y_test, y_pred, average='weighted'):.5f}\nroc_auc is {roc_auc_score(y_test, y_pred_proba, multi_class='ovo', average='weighted'):.5f}")

accuracy is 0.92899
precision is 0.93009
recall is 0.92899
roc_auc is 0.99033

### 5. Прогнозы
 
1. Выберите лучшую модель. Вы можете задаться вопросом, с точки зрения какой метрики, но при расчете вам станет всё очевидно.
2. Проанализируйте: для какого дня недели модель делает больше всего ошибок (в % от общего количество наблюдений этого класса в вашем датасете). Также проанализируйте на какой лаборатороной работе и на каком юзере модель делает больше всего ошибок уже вне зависимости от дней недели.
3. Сохраните модель.

Лучшая модель *RandomForestClassifier* по всем метрикам

In [25]:
for day in range(7):
    print(f'day:{day}, mistakes: {sum((y_test != rf.predict(X_test)) & (y_test == day)) / sum(y_test == day)*100:.3f}%')

day:0, mistakes: 25.926%
day:1, mistakes: 10.909%
day:2, mistakes: 6.667%
day:3, mistakes: 2.500%
day:4, mistakes: 14.286%
day:5, mistakes: 5.556%
day:6, mistakes: 1.408%

Больше всего классификатор ошибается для понедельника в 22.222%

In [26]:
for column in X.columns:
    if 'user' in column:
        print(f'user: {column}, mistakes: ', end='')
        if len (X_test[X_test[column] == 1.0]) > 0:
            print(f'{1 - accuracy_score(y_test[X_test[column] == 1.0], rf.predict(X_test[X_test[column] == 1.0])):.3%}')
        else:
            print('not in test')

user: uid_user_0, mistakes: not in test
user: uid_user_1, mistakes: 0.000%
user: uid_user_10, mistakes: 8.333%
user: uid_user_11, mistakes: not in test
user: uid_user_12, mistakes: 0.000%
user: uid_user_13, mistakes: 0.000%
user: uid_user_14, mistakes: 3.226%
user: uid_user_15, mistakes: 0.000%
user: uid_user_16, mistakes: 40.000%
user: uid_user_17, mistakes: 0.000%
user: uid_user_18, mistakes: 16.667%
user: uid_user_19, mistakes: 21.053%
user: uid_user_2, mistakes: 3.571%
user: uid_user_20, mistakes: 0.000%
user: uid_user_21, mistakes: 0.000%
user: uid_user_22, mistakes: 100.000%
user: uid_user_23, mistakes: 0.000%
user: uid_user_24, mistakes: 9.091%
user: uid_user_25, mistakes: 9.091%
user: uid_user_26, mistakes: 0.000%
user: uid_user_27, mistakes: 16.667%
user: uid_user_28, mistakes: 0.000%
user: uid_user_29, mistakes: 9.091%
user: uid_user_3, mistakes: 14.286%
user: uid_user_30, mistakes: 12.500%
user: uid_user_31, mistakes: 11.111%
user: uid_user_4, mistakes: 7.407%
user: uid_user_6, mistakes: 25.000%
user: uid_user_7, mistakes: not in test
user: uid_user_8, mistakes: 0.000%

Классификатор чаще всего ошибается для *uid_user_22* в 100% случаев, 
*uid_user_0, uid_user_11, uid_user_7* нет в тестовой выборке

In [32]:
for column in X.columns:
    if 'labname' in column:
        print(f'labname: {column}, mistakes: ', end='')
        if len (X_test[X_test[column] == 1.0]) > 0:
            print(f'{1 - accuracy_score(y_test[X_test[column] == 1.0], rf.predict(X_test[X_test[column] == 1.0])):.3%}')
        else:
            print('not in test')

labname: labname_code_rvw, mistakes: 7.692%
labname: labname_lab02, mistakes: not in test
labname: labname_lab03, mistakes: 100.000%
labname: labname_lab03s, mistakes: 100.000%
labname: labname_lab05s, mistakes: 16.667%
labname: labname_laba04, mistakes: 17.143%
labname: labname_laba04s, mistakes: 0.000%
labname: labname_laba05, mistakes: 2.128%
labname: labname_laba06, mistakes: 22.222%
labname: labname_laba06s, mistakes: 13.333%
labname: labname_project1, mistakes: 4.839%

Классификатор чаще всего ошибается для *labname_lab03, labname_lab03s* в 100% случаев, 
*labname_lab02* нет в тестовой выборке

### 6. Функция
 
1. Напишите функцию, которая принимает на вход список разных моделей и соответствующий модели список параметров в виде словаря. Функция возвращает словарь, который содержит все 4 метрики, расмотренных в этом задании, для каждой модели из списка. 
{'model1': {'accuracy': 0.7, 'precision': 0.5, ... },'model2': {...}}

In [35]:
def metrics(estimaters, params, X_train, y_train, X_test, y_test):
    result = dict()
    for i in range(len(estimaters)):
        estimater = estimaters[i].set_params(**params[i])
        estimater.fit(X_train, y_train)
        y_pred = estimater.predict(X_test)
        y_pred_proba = estimater.predict_proba(X_test)
        result['model' + str(i + 1)] = dict()
        result['model' + str(i + 1)]['accuracy'] = accuracy_score(y_test, y_pred)
        result['model' + str(i + 1)]['precision'] = precision_score(y_test, y_pred, average='weighted')
        result['model' + str(i + 1)]['recall'] = recall_score(y_test, y_pred, average='weighted')
        result['model' + str(i + 1)]['rocauc'] = roc_auc_score(y_test, y_pred_proba, average='weighted', multi_class='ovo')
    return result

In [36]:
metrics([SVC(), DecisionTreeClassifier(), RandomForestClassifier()],
        [
            {'C': 10,
            'class_weight': None,
            'gamma': 'auto',
            'kernel': 'rbf',
            'random_state': 21,
            'probability': True},
            {'class_weight': 'balanced',
            'criterion': 'gini',
            'max_depth': 21,
            'random_state': 21},
            {'class_weight': None,
            'criterion': 'gini',
            'max_depth': 28,
            'n_estimators': 50,
            'random_state': 21}
        ], X_train, y_train, X_test, y_test)

{'model1': {'accuracy': 0.8875739644970414,
  'precision': 0.8926729169690374,
  'recall': 0.8875739644970414,
  'rocauc': 0.9787793228216216},
 'model2': {'accuracy': 0.8905325443786982,
  'precision': 0.8940158937843722,
  'recall': 0.8905325443786982,
  'rocauc': 0.9379290651156622},
 'model3': {'accuracy': 0.9289940828402367,
  'precision': 0.9300865038851309,
  'recall': 0.9289940828402367,
  'rocauc': 0.9903274757720744}}